package ORM_DB;
// Generated Jun 21, 2018 10:07:31 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payments generated by hbm2java
 */
public class Payments  implements java.io.Serializable {


     private int id;
     private String memId;
     private String typeOfPayment;
     private float amount;
     private Date date;
     private Date time;

    public Payments() {
    }

    public Payments(int id, String memId, String typeOfPayment, float amount, Date date, Date time) {
       this.id = id;
       this.memId = memId;
       this.typeOfPayment = typeOfPayment;
       this.amount = amount;
       this.date = date;
       this.time = time;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMemId() {
        return this.memId;
    }
    
    public void setMemId(String memId) {
        this.memId = memId;
    }
    public String getTypeOfPayment() {
        return this.typeOfPayment;
    }
    
    public void setTypeOfPayment(String typeOfPayment) {
        this.typeOfPayment = typeOfPayment;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


