package ORM_DB;
// Generated Jun 21, 2018 10:07:31 AM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String id;
     private String password;
     private String status;

    public Users() {
    }

    public Users(String id, String password, String status) {
       this.id = id;
       this.password = password;
       this.status = status;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


